services:
  database:
    image: postgres:15.1-alpine
    container_name: xalt_postgres
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: